### ISSUE TITLE
Error on running gloss2pose.py

### ISSUE THREAD

**Issue by hshreeshail** [stephstoll91/SignSynth#2]
On running python `gloss2pose.py`, I am getting the following error
```
Traceback (most recent call last):
  File "gloss2pose.py", line 409, in <module>
    g2p = gloss2pose(args)
  File "gloss2pose.py", line 36, in __init__
    self.X, self.Y, self.Xdim, self.Ydim, self.samples, self.Xmean, self.Xstd, self.Ymean, self.Ystd, self.lab, self.label_dim, self.Lmean, self.Lstd, self.labo, self.label_o_dim, self.Lomean, self.Lostd, self.L_den = self.get_data(
  File "gloss2pose.py", line 80, in get_data
    data = np.load(data_path)
  File "/data/envs/ohdev/lib/python3.8/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/steph/Documents/Chapter3/Code/pose_regressor_pytorch-master/data/new_normed_smile_data_input_train_eval_test_subset.npz'
```

Could you please provide the files required to run the code in this repository?

Thanks.

**Comment by hshreeshail** [comment]
Alternatively, could you provide the values of `Xdim`, `Ydim` and `label_dim` required to initialize the `pose_regressor` since those values are obtained from the `new_normed_smile_data_input_train_eval_test_subset.npz` file
